### ISSUE TITLE
firefox

### ISSUE THREAD

**Issue by koloved** [rodewitsch/PuzzleEnglishDictionary#20]
есть ли какой способ установить это на фокс? пытался через waterfox, не вышло, эх... (

**Comment by rodewitsch** [comment]
я думал над портированием под firefox, но не доходили руки.
попробую в ближайшее время заняться этим вопросом.

**Comment by rodewitsch** [comment]
Опубликовал версию, пока экспериментальная ветка. Надо потестить чуток. 
https://addons.mozilla.org/ru/firefox/addon/puzzle-english-dict-unofficial/

**Comment by koloved** [comment]
Ого, круто ! вы так быстро переписали, невероятно! пользуюсь уже 4 дня, полет отличный, пока ничего не крашилось
